### ISSUE TITLE
Icons show a dark box on hover

### ISSUE THREAD

**Issue by pexeixv** [vidyadhari4/GithubProfile#7]
![image](https://user-images.githubusercontent.com/68476117/137879224-f9755b5d-9cbd-4ebc-a83d-634347057007.png)

The social media icons show a dark grey box on hover. Check the Twitter icon in the above ss.
Assign me this issue and I will fix it under Hacktoberfest.

**Comment by vidyadhari4** [comment]
I have assigned this issue to you. I am really new to open source and might mess up something. So please only change things related to the grey box in the background. Thank you!

**Comment by pexeixv** [comment]
Solved in PR #8
